[package]
name = "siter"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gobble = {path="../gobble/"}
gtmpl_value = "0.3.3"
toml = "0.5.6"
anyhow = "1.0.31"
thiserror = "1.0.20"
pulldown-cmark = "0.7.2"
gtmpl_helpers = "0.1.3"
gtmpl = "0.5.7"
